-- Seed data for Maharashtra districts
-- This file contains the 36 districts of Maharashtra with their codes and names

INSERT INTO "districts" (id, code, name, "nameHi", "nameMr", "stateCode", "stateName", "createdAt", "updatedAt") VALUES
  ('dist_1', 'MH_MUMBAI', 'Mumbai', 'मुंबई', 'मुंबई', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_2', 'MH_PUNE', 'Pune', 'पुणे', 'पुणे', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_3', 'MH_NAGPUR', 'Nagpur', 'नागपुर', 'नागपूर', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_4', 'MH_THANE', 'Thane', 'ठाणे', 'ठाणे', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_5', 'MH_NASHIK', 'Nashik', 'नासिक', 'नाशिक', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_6', 'MH_AURANGABAD', 'Aurangabad', 'औरंगाबाद', 'औरंगाबाद', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_7', 'MH_SOLAPUR', 'Solapur', 'सोलापुर', 'सोलापूर', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_8', 'MH_AMRAVATI', 'Amravati', 'अमरावती', 'अमरावती', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_9', 'MH_NANDED', 'Nanded', 'नांदेड', 'नांदेड', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_10', 'MH_KOLHAPUR', 'Kolhapur', 'कोल्हापुर', 'कोल्हापूर', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_11', 'MH_AHMEDNAGAR', 'Ahmednagar', 'अहमदनगर', 'अहमदनगर', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_12', 'MH_AKOLA', 'Akola', 'अकोला', 'अकोला', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_13', 'MH_JALGAON', 'Jalgaon', 'जलगांव', 'जळगाव', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_14', 'MH_LATUR', 'Latur', 'लातूर', 'लातूर', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_15', 'MH_DHULE', 'Dhule', 'धुले', 'धुळे', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_16', 'MH_BULDANA', 'Buldana', 'बुलढाणा', 'बुलडाणा', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_17', 'MH_JALNA', 'Jalna', 'जालना', 'जालना', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_18', 'MH_SANGLI', 'Sangli', 'सांगली', 'सांगली', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_19', 'MH_SATARA', 'Satara', 'सातारा', 'सातारा', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_20', 'MH_RAIGAD', 'Raigad', 'रायगड', 'रायगड', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_21', 'MH_BEED', 'Beed', 'बीड', 'बीड', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_22', 'MH_YAVATMAL', 'Yavatmal', 'यवतमाल', 'यवतमाळ', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_23', 'MH_PARBHANI', 'Parbhani', 'परभणी', 'परभणी', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_24', 'MH_CHANDRAPUR', 'Chandrapur', 'चंद्रपुर', 'चंद्रपूर', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_25', 'MH_WARDHA', 'Wardha', 'वर्धा', 'वर्धा', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_26', 'MH_NANDURBAR', 'Nandurbar', 'नंदुरबार', 'नंदुरबार', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_27', 'MH_OSMANABAD', 'Osmanabad', 'उस्मानाबाद', 'उस्मानाबाद', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_28', 'MH_GONDIA', 'Gondia', 'गोंदिया', 'गोंदिया', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_29', 'MH_BHANDARA', 'Bhandara', 'भंडारा', 'भंडारा', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_30', 'MH_WASHIM', 'Washim', 'वाशिम', 'वाशिम', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_31', 'MH_HINGOLI', 'Hingoli', 'हिंगोली', 'हिंगोली', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_32', 'MH_GADCHIROLI', 'Gadchiroli', 'गढ़चिरौली', 'गडचिरोली', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_33', 'MH_RATNAGIRI', 'Ratnagiri', 'रत्नागिरी', 'रत्नागिरी', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_34', 'MH_SINDHUDURG', 'Sindhudurg', 'सिंधुदुर्ग', 'सिंधुदुर्ग', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_35', 'MH_PALGHAR', 'Palghar', 'पालघर', 'पालघर', 'MH', 'Maharashtra', NOW(), NOW()),
  ('dist_36', 'MH_MUMBAI_SUBURBAN', 'Mumbai Suburban', 'मुंबई उपनगरीय', 'मुंबई उपनगर', 'MH', 'Maharashtra', NOW(), NOW())
ON CONFLICT (code) DO NOTHING;
